# Generated by Django 2.1.5 on 2019-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boston_code_camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='RoomName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='RoomName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='SessionName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='Speaker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='TimeSlot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
