# Generated by Django 2.1.5 on 2019-03-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boston_code_camp', '0002_auto_20190316_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='RoomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boston_code_camp.Room'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boston_code_camp.Speaker'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
