# Generated by Django 2.1.5 on 2019-03-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boston_code_camp', '0003_auto_20190316_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='TimeSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boston_code_camp.TimeSlot'),
        ),
    ]
