# Generated by Django 2.1.5 on 2019-03-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boston_code_camp', '0004_auto_20190316_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='EndTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='StartTime',
            field=models.TimeField(),
        ),
    ]
